export type FeaturedItem = { id: string; name: string; kind: "Image model" | "Video model"; tagline: string; vendor: string; price: string; poster: string; video: string | null; };
/* NOTE: all previews are unique royalty-free stock (Pexels) matched per
   model — never the competitor's CDN assets. Videos: muted loops.
   Posters double as the video poster frame. */
export const FEATURED: FeaturedItem[] = [
  {
    id: "seedance-2.5",
    name: "Seedance 2.5",
    kind: "Video model",
    tagline: "Text-to-video with sound and up to 30s cuts",
    vendor: "ByteDance",
    price: "from $0.0864/s",
    poster: "https://images.pexels.com/photos/3624368/pexels-photo-3624368.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: "https://videos.pexels.com/video-files/30739577/13149274_1280_720_25fps.mp4",
  },
  {
    id: "soul-2",
    name: "Soul 2",
    kind: "Image model",
    tagline: "Generate portraits and scenes from written prompts.",
    vendor: "Higgsfield",
    price: "$0.0032/img",
    poster: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: null,
  },
  {
    id: "kling-3-std",
    name: "Kling 3.0 Standard",
    kind: "Video model",
    tagline: "Automatically adapts to your references.",
    vendor: "Kling",
    price: "from $0.042/s",
    poster: "https://images.pexels.com/photos/30548738/pexels-photo-30548738.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: "https://videos.pexels.com/video-files/30789824/13169564_720_1280_60fps.mp4",
  },
  {
    id: "qwen-image-3",
    name: "Qwen Image 3",
    kind: "Image model",
    tagline: "Generate images from Chinese or English prompts.",
    vendor: "Alibaba",
    price: "$0.04/img",
    poster: "https://images.pexels.com/photos/2050297/pexels-photo-2050297.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: null,
  },
  {
    id: "minimax-h3",
    name: "MiniMax H3",
    kind: "Video model",
    tagline: "Lifelike action with expressive motion",
    vendor: "MiniMax",
    price: "from $0.0715/s",
    poster: "https://images.pexels.com/photos/35462271/pexels-photo-35462271.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: "https://videos.pexels.com/video-files/36019280/15274634_720_1280_24fps.mp4",
  },
  {
    id: "grok-imagine-2",
    name: "Grok Imagine 2.0",
    kind: "Image model",
    tagline: "Generate images from prompts or edit references",
    vendor: "xAI",
    price: "$0.04/img",
    poster: "https://images.pexels.com/photos/6818644/pexels-photo-6818644.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: null,
  },
  {
    id: "genjutsu-motion",
    name: "Genjutsu Motion Transfer",
    kind: "Video model",
    tagline: "Restyle one clip into endless new looks",
    vendor: "Higgsfield",
    price: "from $0.159/s",
    poster: "https://images.pexels.com/photos/3902726/pexels-photo-3902726.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: "https://videos.pexels.com/video-files/10264582/10264582-hd_720_1366_25fps.mp4",
  },
  {
    id: "ideogram-4",
    name: "Ideogram 4.0",
    kind: "Image model",
    tagline: "Crisp text in images plus edits",
    vendor: "Ideogram",
    price: "$0.03/img",
    poster: "https://images.pexels.com/photos/8485065/pexels-photo-8485065.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: null,
  },
  {
    id: "wan-3-prime",
    name: "Wan 3.0 Prime",
    kind: "Video model",
    tagline: "Sharp prompt-driven clips in seconds",
    vendor: "Alibaba",
    price: "from $0.0476/s",
    poster: "https://images.pexels.com/photos/6431040/pexels-photo-6431040.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: "https://videos.pexels.com/video-files/7385122/7385122-hd_1280_720_30fps.mp4",
  },
  {
    id: "recraft-4.1",
    name: "Recraft 4.1",
    kind: "Image model",
    tagline: "Clean graphics with custom colors",
    vendor: "Recraft",
    price: "$0.035/img",
    poster: "https://images.pexels.com/photos/8760862/pexels-photo-8760862.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: null,
  },
  {
    id: "cinema-studio-4",
    name: "Cinema Studio 4.0",
    kind: "Video model",
    tagline: "Auto-directed scenes with film feel",
    vendor: "Higgsfield",
    price: "from $0.2057/s",
    poster: "https://images.pexels.com/photos/7991303/pexels-photo-7991303.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: "https://videos.pexels.com/video-files/7984156/7984156-hd_720_1366_25fps.mp4",
  },
  {
    id: "wan-3",
    name: "Wan 3.0",
    kind: "Video model",
    tagline: "Everyday text prompts to smooth video",
    vendor: "Alibaba",
    price: "from $0.03/s",
    poster: "https://images.pexels.com/photos/9439261/pexels-photo-9439261.jpeg?auto=compress&cs=tinysrgb&w=800",
    video: "https://videos.pexels.com/video-files/34218267/14503025_1280_720_60fps.mp4",
  },
];
